// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProgress(arg1) {
  return window['go']['main']['App']['GetProgress'](arg1);
}

export function OpenDirectoryBrowser(arg1) {
  return window['go']['main']['App']['OpenDirectoryBrowser'](arg1);
}

export function ReadAnalysis(arg1) {
  return window['go']['main']['App']['ReadAnalysis'](arg1);
}

export function StartAnalysing(arg1, arg2) {
  return window['go']['main']['App']['StartAnalysing'](arg1, arg2);
}
