// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {reader} from '../models';
import {main} from '../models';

export function GetProgress():Promise<reader.Progress>;

export function Greet(arg1:string):Promise<string>;

export function OpenFileBrowser(arg1:number):Promise<main.SelectedDirectory>;

export function ReadTacviewTimes(arg1:number,arg2:Array<string>):Promise<reader.TimesResult>;
